<a href="https://colab.research.google.com/github/YashsTiwari/ML_DL_revision/blob/main/Coding_Manual_pytorch_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [40]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [41]:
df.shape

(569, 33)

In [42]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [43]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [44]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [45]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [46]:
X_train

array([[-0.42440857, -0.47846367, -0.4498273 , ..., -0.87072339,
        -0.33553205, -0.80029229],
       [-0.52001258,  1.72055925, -0.45402814, ...,  0.51083193,
         0.5554486 ,  2.11565935],
       [ 0.60985297, -0.14032939,  0.70750523, ...,  0.93046323,
        -0.19689749,  1.31351845],
       ...,
       [-0.69383805, -1.07882453, -0.657349  , ..., -0.10862378,
        -0.47754794,  0.88928759],
       [ 1.45870067,  1.24671122,  1.69890441, ...,  0.98426211,
         0.48951265,  1.08756327],
       [-0.13180237, -0.70158629, -0.17635236, ..., -0.39391157,
        -0.13603354, -0.29528245]])

In [47]:
y_train

325    B
193    M
283    M
426    B
324    B
      ..
258    M
394    B
510    B
12     M
532    B
Name: diagnosis, Length: 455, dtype: object

In [48]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [49]:
y_train

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,

In [50]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [51]:
X_train_tensor.shape

torch.Size([455, 30])

## Defining the model

In [55]:
class SimpleNN():

  def __init__(self,X):
    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z=torch.mm(X,self.weights)+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred

  def loss(self, y_pred, y):
    ep=1e-7
    y_pred=torch.clamp(y_pred,ep,1-ep)
    loss=-(y_train_tensor*torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()
    return loss


In [63]:
learning_rate=0.01
epochs=100

In [64]:
#creating model
model=SimpleNN(X_train_tensor)

#defining loop
for epoch in range(epochs):
  y_pred=model.forward(X_train_tensor)  #forward pass
  loss=model.loss(y_pred,y_train_tensor)  #cal. loss
  loss.backward()  #backprop

  with torch.no_grad():
    model.weights-=learning_rate*model.weights.grad  #updating weights
    model.bias-=learning_rate*model.bias.grad   #updating bias

#zero gradient
    model.weights.grad.zero_()
    model.bias.grad.zero_()

  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.388410848031032
Epoch: 2, Loss: 3.3749214013438413
Epoch: 3, Loss: 3.3614476947303444
Epoch: 4, Loss: 3.3479899256005066
Epoch: 5, Loss: 3.3345482930987163
Epoch: 6, Loss: 3.3211229981139394
Epoch: 7, Loss: 3.307714243256188
Epoch: 8, Loss: 3.29432223287037
Epoch: 9, Loss: 3.2809471730316524
Epoch: 10, Loss: 3.267589271521214
Epoch: 11, Loss: 3.2542487378570866
Epoch: 12, Loss: 3.2409257832678025
Epoch: 13, Loss: 3.2276206207064373
Epoch: 14, Loss: 3.2142647070148453
Epoch: 15, Loss: 3.2007260721738264
Epoch: 16, Loss: 3.18720646838445
Epoch: 17, Loss: 3.173706125475272
Epoch: 18, Loss: 3.160225275104939
Epoch: 19, Loss: 3.1467113370446733
Epoch: 20, Loss: 3.1330035286207822
Epoch: 21, Loss: 3.119316542866628
Epoch: 22, Loss: 3.105650629259035
Epoch: 23, Loss: 3.0919976050357043
Epoch: 24, Loss: 3.07808557022674
Epoch: 25, Loss: 3.064030149631865
Epoch: 26, Loss: 3.049997373868576
Epoch: 27, Loss: 3.03598751485148
Epoch: 28, Loss: 3.0220008468316557
Epoch: 29, Loss: 3

In [65]:
model.weights

tensor([[-2.2457e-01],
        [ 3.2517e-01],
        [ 3.4210e-01],
        [ 3.6840e-01],
        [ 3.5345e-04],
        [-2.6302e-01],
        [ 4.7405e-01],
        [ 3.7804e-01],
        [ 4.2649e-01],
        [ 8.8119e-01],
        [-1.4483e-01],
        [ 8.1288e-01],
        [ 6.4442e-01],
        [-1.6320e-02],
        [ 4.5916e-02],
        [ 2.1354e-01],
        [ 5.1365e-01],
        [ 1.9708e-01],
        [ 2.5498e-01],
        [ 1.6007e-01],
        [ 4.3947e-02],
        [ 2.8893e-01],
        [-1.4747e-01],
        [ 4.6844e-01],
        [ 5.5348e-01],
        [-2.3460e-01],
        [ 6.8139e-01],
        [ 2.2419e-01],
        [ 6.0245e-01],
        [ 5.6590e-03]], dtype=torch.float64, requires_grad=True)

In [66]:
model.bias

tensor([-0.0357], dtype=torch.float64, requires_grad=True)

## Evaluation

In [68]:
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  y_pred=(y_pred>0.5).float()
  accuracy=(y_pred==y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5236995816230774
